ci:
  validate:
    swift-format: true
    headers:
      license:
        name: Apache License v2.0
        identifier: Apache-2.0
  env:
    AWS_ACCESS_KEY_ID: "MYACCESSKEYID"
    AWS_SECRET_ACCESS_KEY: "MYSECRETACCESSKEY"
    LOCALSTACK_ENDPOINT: "http://localstack:4566"
  # Enable Linux CI
  linux:
    # Docker container to use in linux CI
    images: ['swift:6.0', 'swiftlang/swift:nightly-6.1-jammy']
    services: |
      localstack:
              image: localstack/localstack