# run this with docker-compose -f docker/docker-compose.yml run test
version: "3.3"

services:
  common: &common
    build: .
    volumes:
      - ..:/working
    working_dir: /working

  test:
    <<: *common
    build: .
    volumes:
      - ..:/working
    working_dir: /working
    depends_on:
      - localstack
    environment:
      - USE_LOCALSTACK=true
    command: /bin/bash -xcl "swift test"

  localstack:
    image: localstack/localstack
