services:
  test:
    image: swift:6.0
    volumes:
      - .:/working
    working_dir: /working
    depends_on:
      - localstack
    environment:
      - LOCALSTACK_ENDPOINT="http://localstack:4566"
    command: /bin/bash -xcl "swift test"

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
